
import { strategyGenerationService } from './services/recommendations/strategy-generation.service';
import { recommendationContentService } from './services/recommendations/recommendation-content.service';
import { mcpSearchService } from './services/data-collection/mcp-search.service';

const TEST_CUSTOMER_ID = '9fd76f75-cc0f-4e6c-b83a-aaa7718a56b2';
const TEST_REC_ID = '0b5a7864-5c63-44e4-aed3-72302052a1c4'; // White paper recommendation

async function runE2ETest() {
    console.log('🚀 Starting End-to-End MCP Search Test...');
    console.log(`Customer: ${TEST_CUSTOMER_ID}`);
    console.log(`Recommendation: ${TEST_REC_ID}`);

    try {
        // 0. Verify Search Connectivity
        console.log('\n--- Step 0: Pre-flight Search Check ---');
        const healthCheck = await mcpSearchService.quickSearch('test', 1);
        if (healthCheck.results.length > 0) {
            console.log('✅ Search Service is ONLINE and responding.');
        } else {
            console.warn('⚠️ Search Service returned no results, but might be reachable.');
        }

        // 1. Generate Strategy (Trigger Trend Search)
        console.log('\n--- Step 1: Strategy Generation (Trend Search) ---');
        console.log('Invoking strategyGenerationService.generateStrategy...');

        // Create dummy template sections as if coming from frontend
        const templateSections = [
            { id: 'intro', title: 'Introduction', content: 'Define the problem.', sectionType: 'intro' },
            { id: 'body', title: 'Main Body', content: 'Discuss solutions.', sectionType: 'body' }
        ];

        const stratResult = await strategyGenerationService.generateStrategy({
            recommendationId: TEST_REC_ID,
            customerId: TEST_CUSTOMER_ID,
            templateSections: templateSections,
            contentType: 'whitepaper',
            customInstructions: 'Focus on enterprise scale.'
        });

        if (stratResult.success && stratResult.data) {
            console.log('✅ Strategy Generated Successfully!');
            if (stratResult.data.researchQueries && stratResult.data.researchQueries.length > 0) {
                console.log(`✅ LLM Generated ${stratResult.data.researchQueries.length} Research Queries:`);
                console.log(stratResult.data.researchQueries);
            } else {
                console.warn('⚠️ No research queries generated by LLM (Check Prompt/Model).');
            }
        } else {
            console.error('❌ Strategy Generation Failed:', stratResult.error);
            return; // Stop if strategy fails
        }

        // 2. Generate Content (Trigger Deep Research)
        console.log('\n--- Step 2: Content Generation (Fact Gathering) ---');
        // We don't need to pass much, as it pulls from the DB (including the strategy we just saved)
        const contentResult = await recommendationContentService.generateContent(
            TEST_REC_ID,
            TEST_CUSTOMER_ID,
            { contentType: 'whitepaper' } // Matching the strategy type
        );

        if (contentResult && contentResult.record) {
            console.log('✅ Content Generated Successfully!');
            console.log('--- Content Sneak Peek ---');
            console.log(contentResult.record.content.substring(0, 500) + '...');

            // Check for evidence of research in the content (heuristic)
            if (contentResult.record.content.includes('Based on') || contentResult.record.content.includes('According to')) {
                console.log('✅ Content appears to cite sources/facts.');
            }
        } else {
            console.error('❌ Content Generation Failed.');
        }

    } catch (error: any) {
        console.error('❌ E2E Test Failed:', error.message);
        console.error(error.stack);
    }
}

runE2ETest();
