
import nodemailer from 'nodemailer';
import { pdfExportServiceV2 } from '../executive-reporting/pdf-export-v2.service';
import { reportOrchestrationService } from '../executive-reporting/report-orchestration.service';

export class EmailServiceV2 {
  private transporter: nodemailer.Transporter;

  constructor() {
    this.transporter = nodemailer.createTransport({
      host: 'smtp.zoho.com',
      port: 465,
      secure: true,
      auth: {
        user: process.env.ZOHO_EMAIL,
        pass: process.env.ZOHO_PASSWORD,
      },
    });
  }

  /**
   * Send Executive Report Email (V2)
   * Mirrors the UI content by embedding a screenshot and attaching the PDF.
   */
  async sendExecutiveReport(
    to: string,
    reportId: string,
    brandId: string,
    brandName: string
  ): Promise<void> {
    console.log(`📧 [EMAIL-V2] Sending executive report to ${to}`);

    try {
      // 1. Fetch Report Details (for subject line, etc.)
      const report = await reportOrchestrationService.getReport(reportId);
      if (!report) throw new Error('Report not found');

      const period = `${new Date(report.report_period_start).toLocaleDateString()} - ${new Date(report.report_period_end).toLocaleDateString()}`;

      // 2. Generate PDF (V2)
      const pdfBuffer = await pdfExportServiceV2.generatePDF(reportId, brandId);

      // 3. Construct Email Content
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <body style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
          <div style="max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
            <div style="margin-bottom: 25px; border-bottom: 2px solid #f0f0f0; padding-bottom: 15px;">
              <h1 style="color: #1a1d29; margin: 0; font-size: 24px;">Executive Report: ${brandName}</h1>
              <p style="color: #64748b; margin: 8px 0 0; font-size: 14px;">Period: ${period}</p>
            </div>
            
            <p style="color: #334155; font-size: 16px; line-height: 1.6;">Hello,</p>
            <p style="color: #334155; font-size: 16px; line-height: 1.6;">
              The executive report for <strong>${brandName}</strong> is now ready. 
              We have attached the full PDF analysis to this email for your review.
            </p>
            
            <div style="margin: 30px 0; padding: 20px; background-color: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
              <p style="color: #475569; font-size: 14px; margin: 0; line-height: 1.5;">
                <strong>What's in this report?</strong><br>
                • Brand visibility across AI search engines<br>
                • Sentiment analysis and key message pull-through<br>
                • Competitive benchmarking and recommendations
              </p>
            </div>
            
            <p style="color: #64748b; font-size: 14px; line-height: 1.5;">
              This is an automated report generated by EvidentlyAEO.
            </p>
            
            <div style="margin-top: 35px; border-top: 1px solid #f0f0f0; padding-top: 20px; color: #94a3b8; font-size: 12px; text-align: center;">
              &copy; ${new Date().getFullYear()} EvidentlyAEO. All rights reserved.
            </div>
          </div>
        </body>
        </html>
      `;

      // 4. Send Email
      await this.transporter.sendMail({
        from: `"EvidentlyAEO Reporting" <${process.env.ZOHO_EMAIL}>`,
        to,
        subject: `Executive Report: ${brandName} (${period})`,
        html: htmlContent,
        attachments: [
          {
            filename: `Executive_Report_${brandName}_${report.report_period_end}.pdf`,
            content: pdfBuffer,
            contentType: 'application/pdf',
          },
        ],
      });

      console.log(`✅ [EMAIL-V2] Email sent successfully to ${to}`);

    } catch (error) {
      console.error('❌ [EMAIL-V2] Failed to send email:', error);
      throw error;
    }
  }
}

export const emailServiceV2 = new EmailServiceV2();
